using Scalar.AspNetCore;
using ServiceB.Infrastructure;
using ServiceB.Models;
using Shared.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddServiceDiscovery();
builder.Services.ConfigureHttpClientDefaults(http =>
{
    http.AddServiceDiscovery();
});

// Kubernetes Service Discovery (automatic via labels)
builder.Services.AddSingleton<IKubernetesServiceDiscovery, KubernetesServiceDiscovery>();

// ServiceC Client Factory (Kiota + Automatic Discovery)
// Singleton: URL resolved once at startup, no K8s query per request
builder.Services.AddSingleton<ServiceCClientFactory>();

// Configurar OpenAPI com metadados
builder.Services.AddOpenApi(options =>
{
    options.AddDocumentTransformer((document, context, cancellationToken) =>
    {
        document.Info = new()
        {
            Title = "ServiceB - Products API",
            Version = "1.0.0",
            Description = "API for managing products"
        };
        return Task.CompletedTask;
    });

    // .NET 10 gera "type": ["integer","string"] e "type": ["number","string"]
    // para int/double (OpenAPI 3.1 union). Kiota não consegue mapear union types
    // para tipos C# concretos e usa UntypedNode. Normaliza para tipo único.
    options.AddSchemaTransformer((schema, context, cancellationToken) =>
    {
        if (schema.Format is "int32" or "int64")
        {
            schema.Type = Microsoft.OpenApi.JsonSchemaType.Integer;
            schema.Pattern = null;
        }
        else if (schema.Format is "float" or "double")
        {
            schema.Type = Microsoft.OpenApi.JsonSchemaType.Number;
            schema.Pattern = null;
        }
        return Task.CompletedTask;
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.MapScalarApiReference();
}

app.MapGet("/api/products", () =>
{
    return Results.Ok(new Product[]
    {
        new(1, "Laptop", 999.99),
        new(2, "Mouse", 29.99)
    });
})
.WithName("GetProducts")
.Produces<Product[]>(200);

app.MapGet("/api/products/{id}", (int id) =>
{
    return Results.Ok(new Product(id, $"Product {id}", 99.99));
})
.WithName("GetProductById")
.Produces<Product>(200);

app.MapPut("/api/products/{id}", (int id, object product) =>
{
    return Results.Ok(new Product(id, "Updated Product", 149.99));
})
.WithName("UpdateProduct")
.Produces<Product>(200);

app.MapGet("/api/products/with-orders/{id}", async (
    IHttpClientFactory httpClientFactory,
    IKubernetesServiceDiscovery k8sDiscovery,
    IConfiguration configuration) =>
{
    try
    {
        // 1. Try automatic discovery via K8s API (if running in cluster)
        var serviceUrl = await k8sDiscovery.DiscoverServiceUrlAsync("orders-api");

        // 2. Fall back to manual configuration (appsettings or env vars)
        if (string.IsNullOrEmpty(serviceUrl))
        {
            serviceUrl = configuration["Services:ServiceC:Url"] ?? "http://servicec";
        }

        var httpClient = httpClientFactory.CreateClient();
        httpClient.BaseAddress = new Uri(serviceUrl);
        httpClient.DefaultRequestHeaders.Add("User-Agent", "ServiceB");

        var response = await httpClient.GetAsync("/api/orders");
        var content = await response.Content.ReadAsStringAsync();

        return Results.Ok(new
        {
            Message = "ServiceB called ServiceC via service discovery",
            DiscoveredUrl = serviceUrl,
            Orders = content
        });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { error = ex.Message, stackTrace = ex.StackTrace });
    }
})
.WithName("GetProductWithOrders")
.Produces(200)
.Produces(400);

// Endpoint using Kiota + Automatic Discovery
app.MapGet("/api/products/with-orders-typed/{id}", async (int id, ServiceCClientFactory clientFactory) =>
{
    try
    {
        // Create Kiota client with automatically discovered URL
        var client = await clientFactory.CreateClientAsync();

        // Type-safe calls using Kiota
        var orders = await client.Api.Orders.GetAsync();

        return Results.Ok(new
        {
            Message = "ServiceB → ServiceC using Kiota + Automatic Discovery",
            Method = "Type-Safe Kiota Client",
            ProductId = id,
            Orders = orders,
            Benefits = new[]
            {
                "✅ URL automatically discovered via K8s labels",
                "✅ Type-safe client generated by Kiota",
                "✅ Full IntelliSense",
                "✅ Compile-time validation"
            }
        });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { error = ex.Message });
    }
})
.WithName("GetProductWithOrdersTyped")
.Produces(200)
.Produces(400);

// Diagnostic endpoint — lists all discovered services
app.MapGet("/api/services/catalog", async (IKubernetesServiceDiscovery k8sDiscovery) =>
{
    var catalog = await k8sDiscovery.DiscoverAllServicesAsync();
    return Results.Ok(new
    {
        Message = "Service catalog from Kubernetes API",
        Services = catalog,
        Count = catalog.Count
    });
})
.WithName("GetServiceCatalog")
.Produces(200);

app.Run();
